sonar.organization=kroshu
sonar.projectName=kuka-external-control-sdk
sonar.projectKey=kroshu_kuka-external-control-sdk

sonar.host.url=https://sonarcloud.io

# analyse SDK implementation sources maintained in this repository
# sonar.modules entry is omitted to avoid module-relative path issues
sonar.sources=./kuka_external_control_sdk_iiqka/iiqka/src,./kuka_external_control_sdk_iiqka/iiqka/include

# Encoding and language settings
sonar.sourceEncoding=UTF-8
sonar.python.version=3
