/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KUKA_ECS_V1_KUKA_ECS_V1_CONTROL_SIGNAL_EXTERNAL_PB_H_INCLUDED
#define PB_KUKA_ECS_V1_KUKA_ECS_V1_CONTROL_SIGNAL_EXTERNAL_PB_H_INCLUDED
#include "pb.h"
#include "test-assets/nanopb/control_signal_internal.pb.h"
#include "test-assets/nanopb/external_header.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Proto definition for external RT commands */
typedef struct _kuka_ecs_v1_ControlSignalExternal {
  /* Message Header */
  bool has_header;
  kuka_ecs_v1_ExternalHeader header;
  /* Internal control signal */
  bool has_control_signal;
  kuka_motion_external_ControlSignalInternal control_signal; /* Later feature for IOs
repeated IOValue io_values = 3; */
} kuka_ecs_v1_ControlSignalExternal;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kuka_ecs_v1_ControlSignalExternal_init_default          \
  {                                                             \
    false, kuka_ecs_v1_ExternalHeader_init_default, false,      \
        kuka_motion_external_ControlSignalInternal_init_default \
  }
#define kuka_ecs_v1_ControlSignalExternal_init_zero          \
  {                                                          \
    false, kuka_ecs_v1_ExternalHeader_init_zero, false,      \
        kuka_motion_external_ControlSignalInternal_init_zero \
  }

/* Field tags (for use in manual encoding/decoding) */
#define kuka_ecs_v1_ControlSignalExternal_header_tag 1
#define kuka_ecs_v1_ControlSignalExternal_control_signal_tag 2

/* Struct field encoding specification for nanopb */
#define kuka_ecs_v1_ControlSignalExternal_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, header, 1)              \
  X(a, STATIC, OPTIONAL, MESSAGE, control_signal, 2)
#define kuka_ecs_v1_ControlSignalExternal_CALLBACK NULL
#define kuka_ecs_v1_ControlSignalExternal_DEFAULT NULL
#define kuka_ecs_v1_ControlSignalExternal_header_MSGTYPE kuka_ecs_v1_ExternalHeader
#define kuka_ecs_v1_ControlSignalExternal_control_signal_MSGTYPE \
  kuka_motion_external_ControlSignalInternal

extern const pb_msgdesc_t kuka_ecs_v1_ControlSignalExternal_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kuka_ecs_v1_ControlSignalExternal_fields &kuka_ecs_v1_ControlSignalExternal_msg

/* Maximum encoded size of messages (where known) */
#if defined(kuka_motion_external_ControlSignalInternal_size)
#define kuka_ecs_v1_ControlSignalExternal_size \
  (20 + kuka_motion_external_ControlSignalInternal_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
