/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "test-assets/nanopb/control_signal_external.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(kuka_ecs_v1_ControlSignalExternal, kuka_ecs_v1_ControlSignalExternal, 4)
