/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KUKA_MOTION_EXTERNAL_KUKA_MOTION_EXTERNAL_CONTROL_SIGNAL_INTERNAL_PB_H_INCLUDED
#define PB_KUKA_MOTION_EXTERNAL_KUKA_MOTION_EXTERNAL_CONTROL_SIGNAL_INTERNAL_PB_H_INCLUDED
#include "pb.h"
#include "test-assets/nanopb/control_attributes.pb.h"
#include "test-assets/nanopb/external_control_mode.pb.h"
#include "test-assets/nanopb/utils.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Proto definition for external RT commands for internal usage on shared memory */
typedef struct _kuka_motion_external_ControlSignalInternal {
  /* Flag for stopping external command handling through RT-channel */
  bool stop_ipo;
  /* The externally calculated joint position command of a joint group. */
  bool has_joint_command;
  kuka_motion_external_JointPositions joint_command;
  /* The externally calculated base to tcp transformation */
  bool has_cartesian_command;
  kuka_motion_external_Transform cartesian_command;
  /* The externally calculated joint velocity command */
  bool has_joint_velocity_command;
  kuka_motion_external_JointVelocities joint_velocity_command;
  /* The externally calculated cartesian velocity (twist) command for the current tcp */
  bool has_twist_command;
  kuka_motion_external_Twist twist_command;
  /* The externally calculated joint torque command of a joint group. */
  bool has_joint_torque_command;
  kuka_motion_external_JointTorques joint_torque_command;
  /* The externally calculated wrench command of a joint group. */
  bool has_wrench_command;
  kuka_motion_external_Wrench wrench_command;
  /* Joint impedance control attributes */
  bool has_joint_attributes;
  kuka_motion_external_JointImpedanceControlAttributes joint_attributes;
  /* Cartesian impedance control attributes */
  bool has_cartesian_attributes;
  kuka_motion_external_CartesianImpedanceControlAttributes cartesian_attributes;
  /* The control mode for the command sent */
  kuka_motion_external_ExternalControlMode control_mode;
} kuka_motion_external_ControlSignalInternal;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kuka_motion_external_ControlSignalInternal_init_default                   \
  {                                                                               \
    0, false, kuka_motion_external_JointPositions_init_default, false,            \
        kuka_motion_external_Transform_init_default, false,                       \
        kuka_motion_external_JointVelocities_init_default, false,                 \
        kuka_motion_external_Twist_init_default, false,                           \
        kuka_motion_external_JointTorques_init_default, false,                    \
        kuka_motion_external_Wrench_init_default, false,                          \
        kuka_motion_external_JointImpedanceControlAttributes_init_default, false, \
        kuka_motion_external_CartesianImpedanceControlAttributes_init_default,    \
        _kuka_motion_external_ExternalControlMode_MIN                             \
  }
#define kuka_motion_external_ControlSignalInternal_init_zero                                      \
  {                                                                                               \
    0, false, kuka_motion_external_JointPositions_init_zero, false,                               \
        kuka_motion_external_Transform_init_zero, false,                                          \
        kuka_motion_external_JointVelocities_init_zero, false,                                    \
        kuka_motion_external_Twist_init_zero, false, kuka_motion_external_JointTorques_init_zero, \
        false, kuka_motion_external_Wrench_init_zero, false,                                      \
        kuka_motion_external_JointImpedanceControlAttributes_init_zero, false,                    \
        kuka_motion_external_CartesianImpedanceControlAttributes_init_zero,                       \
        _kuka_motion_external_ExternalControlMode_MIN                                             \
  }

/* Field tags (for use in manual encoding/decoding) */
#define kuka_motion_external_ControlSignalInternal_stop_ipo_tag 1
#define kuka_motion_external_ControlSignalInternal_joint_command_tag 2
#define kuka_motion_external_ControlSignalInternal_cartesian_command_tag 3
#define kuka_motion_external_ControlSignalInternal_joint_velocity_command_tag 4
#define kuka_motion_external_ControlSignalInternal_twist_command_tag 5
#define kuka_motion_external_ControlSignalInternal_joint_torque_command_tag 6
#define kuka_motion_external_ControlSignalInternal_wrench_command_tag 7
#define kuka_motion_external_ControlSignalInternal_joint_attributes_tag 8
#define kuka_motion_external_ControlSignalInternal_cartesian_attributes_tag 9
#define kuka_motion_external_ControlSignalInternal_control_mode_tag 10

/* Struct field encoding specification for nanopb */
#define kuka_motion_external_ControlSignalInternal_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, BOOL, stop_ipo, 1)                        \
  X(a, STATIC, OPTIONAL, MESSAGE, joint_command, 2)                \
  X(a, STATIC, OPTIONAL, MESSAGE, cartesian_command, 3)            \
  X(a, STATIC, OPTIONAL, MESSAGE, joint_velocity_command, 4)       \
  X(a, STATIC, OPTIONAL, MESSAGE, twist_command, 5)                \
  X(a, STATIC, OPTIONAL, MESSAGE, joint_torque_command, 6)         \
  X(a, STATIC, OPTIONAL, MESSAGE, wrench_command, 7)               \
  X(a, STATIC, OPTIONAL, MESSAGE, joint_attributes, 8)             \
  X(a, STATIC, OPTIONAL, MESSAGE, cartesian_attributes, 9)         \
  X(a, STATIC, SINGULAR, UENUM, control_mode, 10)
#define kuka_motion_external_ControlSignalInternal_CALLBACK NULL
#define kuka_motion_external_ControlSignalInternal_DEFAULT NULL
#define kuka_motion_external_ControlSignalInternal_joint_command_MSGTYPE \
  kuka_motion_external_JointPositions
#define kuka_motion_external_ControlSignalInternal_cartesian_command_MSGTYPE \
  kuka_motion_external_Transform
#define kuka_motion_external_ControlSignalInternal_joint_velocity_command_MSGTYPE \
  kuka_motion_external_JointVelocities
#define kuka_motion_external_ControlSignalInternal_twist_command_MSGTYPE kuka_motion_external_Twist
#define kuka_motion_external_ControlSignalInternal_joint_torque_command_MSGTYPE \
  kuka_motion_external_JointTorques
#define kuka_motion_external_ControlSignalInternal_wrench_command_MSGTYPE \
  kuka_motion_external_Wrench
#define kuka_motion_external_ControlSignalInternal_joint_attributes_MSGTYPE \
  kuka_motion_external_JointImpedanceControlAttributes
#define kuka_motion_external_ControlSignalInternal_cartesian_attributes_MSGTYPE \
  kuka_motion_external_CartesianImpedanceControlAttributes

extern const pb_msgdesc_t kuka_motion_external_ControlSignalInternal_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kuka_motion_external_ControlSignalInternal_fields \
  &kuka_motion_external_ControlSignalInternal_msg

/* Maximum encoded size of messages (where known) */
#define kuka_motion_external_ControlSignalInternal_size 2152

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
