/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KUKA_ECS_V1_KUKA_ECS_V1_EXTERNAL_HEADER_PB_H_INCLUDED
#define PB_KUKA_ECS_V1_KUKA_ECS_V1_EXTERNAL_HEADER_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Proto definition for external RT commands */
typedef struct _kuka_ecs_v1_ExternalHeader {
  /* Message Id */
  uint32_t message_id;
  /* Interpolator message identifier */
  uint32_t ipoc;
} kuka_ecs_v1_ExternalHeader;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kuka_ecs_v1_ExternalHeader_init_default \
  { 0, 0 }
#define kuka_ecs_v1_ExternalHeader_init_zero \
  { 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define kuka_ecs_v1_ExternalHeader_message_id_tag 1
#define kuka_ecs_v1_ExternalHeader_ipoc_tag 2

/* Struct field encoding specification for nanopb */
#define kuka_ecs_v1_ExternalHeader_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UINT32, message_id, 1)    \
  X(a, STATIC, SINGULAR, UINT32, ipoc, 2)
#define kuka_ecs_v1_ExternalHeader_CALLBACK NULL
#define kuka_ecs_v1_ExternalHeader_DEFAULT NULL

extern const pb_msgdesc_t kuka_ecs_v1_ExternalHeader_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kuka_ecs_v1_ExternalHeader_fields &kuka_ecs_v1_ExternalHeader_msg

/* Maximum encoded size of messages (where known) */
#define kuka_ecs_v1_ExternalHeader_size 12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
