/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "test-assets/nanopb/motion_state_internal.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(kuka_motion_external_MotionStateInternal, kuka_motion_external_MotionStateInternal, 4)
