/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KUKA_ECS_V1_KUKA_ECS_V1_MOTION_STATE_EXTERNAL_PB_H_INCLUDED
#define PB_KUKA_ECS_V1_KUKA_ECS_V1_MOTION_STATE_EXTERNAL_PB_H_INCLUDED
#include "pb.h"
#include "test-assets/nanopb/external_header.pb.h"
#include "test-assets/nanopb/motion_state_internal.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* External motion state */
typedef struct _kuka_ecs_v1_MotionStateExternal {
  /* Header containing ID and checksum */
  bool has_header;
  kuka_ecs_v1_ExternalHeader header;
  /* The measured joint position of the current cycle */
  bool has_motion_state;
  kuka_motion_external_MotionStateInternal motion_state; /* IO handling
repeated IOValue io_values = 4; */
} kuka_ecs_v1_MotionStateExternal;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kuka_ecs_v1_MotionStateExternal_init_default          \
  {                                                           \
    false, kuka_ecs_v1_ExternalHeader_init_default, false,    \
        kuka_motion_external_MotionStateInternal_init_default \
  }
#define kuka_ecs_v1_MotionStateExternal_init_zero          \
  {                                                        \
    false, kuka_ecs_v1_ExternalHeader_init_zero, false,    \
        kuka_motion_external_MotionStateInternal_init_zero \
  }

/* Field tags (for use in manual encoding/decoding) */
#define kuka_ecs_v1_MotionStateExternal_header_tag 1
#define kuka_ecs_v1_MotionStateExternal_motion_state_tag 2

/* Struct field encoding specification for nanopb */
#define kuka_ecs_v1_MotionStateExternal_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, header, 1)            \
  X(a, STATIC, OPTIONAL, MESSAGE, motion_state, 2)
#define kuka_ecs_v1_MotionStateExternal_CALLBACK NULL
#define kuka_ecs_v1_MotionStateExternal_DEFAULT NULL
#define kuka_ecs_v1_MotionStateExternal_header_MSGTYPE kuka_ecs_v1_ExternalHeader
#define kuka_ecs_v1_MotionStateExternal_motion_state_MSGTYPE \
  kuka_motion_external_MotionStateInternal

extern const pb_msgdesc_t kuka_ecs_v1_MotionStateExternal_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kuka_ecs_v1_MotionStateExternal_fields &kuka_ecs_v1_MotionStateExternal_msg

/* Maximum encoded size of messages (where known) */
#if defined(kuka_motion_external_MotionStateInternal_size)
#define kuka_ecs_v1_MotionStateExternal_size (20 + kuka_motion_external_MotionStateInternal_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
