/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KUKA_MOTION_EXTERNAL_KUKA_MOTION_EXTERNAL_MOTION_STATE_INTERNAL_PB_H_INCLUDED
#define PB_KUKA_MOTION_EXTERNAL_KUKA_MOTION_EXTERNAL_MOTION_STATE_INTERNAL_PB_H_INCLUDED
#include "pb.h"
#include "test-assets/nanopb/external_control_mode.pb.h"
#include "test-assets/nanopb/utils.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Internal message for SharedMem Communication between ecs and external sampler */
typedef struct _kuka_motion_external_MotionStateInternal {
  /* Flag indicating whether the command handling has stopped */
  bool ipo_stopped;
  /* Currently used control mode */
  kuka_motion_external_ExternalControlMode control_mode;
  /* The measured joint position of the current cycle */
  bool has_measured_positions;
  kuka_motion_external_JointPositions measured_positions;
  /* The measured joint velocities of the current cycle */
  bool has_measured_velocities;
  kuka_motion_external_JointVelocities measured_velocities;
  /* The measured joint torques of the current cycle */
  bool has_measured_torques;
  kuka_motion_external_JointTorques measured_torques;
} kuka_motion_external_MotionStateInternal;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kuka_motion_external_MotionStateInternal_init_default     \
  {                                                               \
    0, _kuka_motion_external_ExternalControlMode_MIN, false,      \
        kuka_motion_external_JointPositions_init_default, false,  \
        kuka_motion_external_JointVelocities_init_default, false, \
        kuka_motion_external_JointTorques_init_default            \
  }
#define kuka_motion_external_MotionStateInternal_init_zero     \
  {                                                            \
    0, _kuka_motion_external_ExternalControlMode_MIN, false,   \
        kuka_motion_external_JointPositions_init_zero, false,  \
        kuka_motion_external_JointVelocities_init_zero, false, \
        kuka_motion_external_JointTorques_init_zero            \
  }

/* Field tags (for use in manual encoding/decoding) */
#define kuka_motion_external_MotionStateInternal_ipo_stopped_tag 1
#define kuka_motion_external_MotionStateInternal_control_mode_tag 2
#define kuka_motion_external_MotionStateInternal_measured_positions_tag 3
#define kuka_motion_external_MotionStateInternal_measured_velocities_tag 4
#define kuka_motion_external_MotionStateInternal_measured_torques_tag 5

/* Struct field encoding specification for nanopb */
#define kuka_motion_external_MotionStateInternal_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, BOOL, ipo_stopped, 1)                   \
  X(a, STATIC, SINGULAR, UENUM, control_mode, 2)                 \
  X(a, STATIC, OPTIONAL, MESSAGE, measured_positions, 3)         \
  X(a, STATIC, OPTIONAL, MESSAGE, measured_velocities, 4)        \
  X(a, STATIC, OPTIONAL, MESSAGE, measured_torques, 5)
#define kuka_motion_external_MotionStateInternal_CALLBACK NULL
#define kuka_motion_external_MotionStateInternal_DEFAULT NULL
#define kuka_motion_external_MotionStateInternal_measured_positions_MSGTYPE \
  kuka_motion_external_JointPositions
#define kuka_motion_external_MotionStateInternal_measured_velocities_MSGTYPE \
  kuka_motion_external_JointVelocities
#define kuka_motion_external_MotionStateInternal_measured_torques_MSGTYPE \
  kuka_motion_external_JointTorques

extern const pb_msgdesc_t kuka_motion_external_MotionStateInternal_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kuka_motion_external_MotionStateInternal_fields \
  &kuka_motion_external_MotionStateInternal_msg

/* Maximum encoded size of messages (where known) */
#define kuka_motion_external_MotionStateInternal_size 661

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
