/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "test-assets/nanopb/utils.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(kuka_motion_external_JointPositions, kuka_motion_external_JointPositions, AUTO)

PB_BIND(kuka_motion_external_JointVelocities, kuka_motion_external_JointVelocities, AUTO)

PB_BIND(kuka_motion_external_JointTorques, kuka_motion_external_JointTorques, AUTO)

PB_BIND(kuka_motion_external_Vector, kuka_motion_external_Vector, AUTO)

PB_BIND(kuka_motion_external_Quaternion, kuka_motion_external_Quaternion, AUTO)

PB_BIND(kuka_motion_external_Twist, kuka_motion_external_Twist, AUTO)

PB_BIND(kuka_motion_external_Wrench, kuka_motion_external_Wrench, AUTO)

PB_BIND(kuka_motion_external_Transform, kuka_motion_external_Transform, AUTO)

#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
