/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KUKA_MOTION_EXTERNAL_KUKA_MOTION_EXTERNAL_UTILS_PB_H_INCLUDED
#define PB_KUKA_MOTION_EXTERNAL_KUKA_MOTION_EXTERNAL_UTILS_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* An array of joint positions for a given kinematic structure. */
typedef struct _kuka_motion_external_JointPositions {
  pb_size_t values_count;
  double values[24];
} kuka_motion_external_JointPositions;

/* An array of joint velocities for a given kinematic structure. */
typedef struct _kuka_motion_external_JointVelocities {
  pb_size_t values_count;
  double values[24];
} kuka_motion_external_JointVelocities;

/* An array of joint torques for a given kinematic structure. */
typedef struct _kuka_motion_external_JointTorques {
  pb_size_t values_count;
  double values[24];
} kuka_motion_external_JointTorques;

/* Represents a vector in 3D space. */
typedef struct _kuka_motion_external_Vector {
  double x;
  double y;
  double z;
} kuka_motion_external_Vector;

/* Represents a quaternion in 3D space. */
typedef struct _kuka_motion_external_Quaternion {
  double x;
  double y;
  double z;
  double w;
} kuka_motion_external_Quaternion;

/* Represents a velocity in 3D space. */
typedef struct _kuka_motion_external_Twist {
  /* The linear part of the velocity. */
  bool has_linear;
  kuka_motion_external_Vector linear;
  /* The angular part of the velocity. */
  bool has_angular;
  kuka_motion_external_Vector angular;
} kuka_motion_external_Twist;

/* Represents force in 3D space. */
typedef struct _kuka_motion_external_Wrench {
  /* The linear components. */
  bool has_force;
  kuka_motion_external_Vector force;
  /* The angular components. */
  bool has_torque;
  kuka_motion_external_Vector torque;
} kuka_motion_external_Wrench;

/* Represents a transform between two coordinate frames in 3D space. */
typedef struct _kuka_motion_external_Transform {
  /* The translational component. */
  bool has_translation;
  kuka_motion_external_Vector translation;
  /* The rotational component. */
  bool has_rotation;
  kuka_motion_external_Quaternion rotation;
} kuka_motion_external_Transform;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kuka_motion_external_JointPositions_init_default                          \
  {                                                                               \
    0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } \
  }
#define kuka_motion_external_JointVelocities_init_default                         \
  {                                                                               \
    0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } \
  }
#define kuka_motion_external_JointTorques_init_default                            \
  {                                                                               \
    0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } \
  }
#define kuka_motion_external_Vector_init_default \
  { 0, 0, 0 }
#define kuka_motion_external_Quaternion_init_default \
  { 0, 0, 0, 0 }
#define kuka_motion_external_Twist_init_default             \
  {                                                         \
    false, kuka_motion_external_Vector_init_default, false, \
        kuka_motion_external_Vector_init_default            \
  }
#define kuka_motion_external_Wrench_init_default            \
  {                                                         \
    false, kuka_motion_external_Vector_init_default, false, \
        kuka_motion_external_Vector_init_default            \
  }
#define kuka_motion_external_Transform_init_default         \
  {                                                         \
    false, kuka_motion_external_Vector_init_default, false, \
        kuka_motion_external_Quaternion_init_default        \
  }
#define kuka_motion_external_JointPositions_init_zero                             \
  {                                                                               \
    0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } \
  }
#define kuka_motion_external_JointVelocities_init_zero                            \
  {                                                                               \
    0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } \
  }
#define kuka_motion_external_JointTorques_init_zero                               \
  {                                                                               \
    0, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } \
  }
#define kuka_motion_external_Vector_init_zero \
  { 0, 0, 0 }
#define kuka_motion_external_Quaternion_init_zero \
  { 0, 0, 0, 0 }
#define kuka_motion_external_Twist_init_zero \
  { false, kuka_motion_external_Vector_init_zero, false, kuka_motion_external_Vector_init_zero }
#define kuka_motion_external_Wrench_init_zero \
  { false, kuka_motion_external_Vector_init_zero, false, kuka_motion_external_Vector_init_zero }
#define kuka_motion_external_Transform_init_zero \
  { false, kuka_motion_external_Vector_init_zero, false, kuka_motion_external_Quaternion_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define kuka_motion_external_JointPositions_values_tag 1
#define kuka_motion_external_JointVelocities_values_tag 1
#define kuka_motion_external_JointTorques_values_tag 1
#define kuka_motion_external_Vector_x_tag 1
#define kuka_motion_external_Vector_y_tag 2
#define kuka_motion_external_Vector_z_tag 3
#define kuka_motion_external_Quaternion_x_tag 1
#define kuka_motion_external_Quaternion_y_tag 2
#define kuka_motion_external_Quaternion_z_tag 3
#define kuka_motion_external_Quaternion_w_tag 4
#define kuka_motion_external_Twist_linear_tag 1
#define kuka_motion_external_Twist_angular_tag 2
#define kuka_motion_external_Wrench_force_tag 1
#define kuka_motion_external_Wrench_torque_tag 2
#define kuka_motion_external_Transform_translation_tag 1
#define kuka_motion_external_Transform_rotation_tag 2

/* Struct field encoding specification for nanopb */
#define kuka_motion_external_JointPositions_FIELDLIST(X, a) \
  X(a, STATIC, REPEATED, DOUBLE, values, 1)
#define kuka_motion_external_JointPositions_CALLBACK NULL
#define kuka_motion_external_JointPositions_DEFAULT NULL

#define kuka_motion_external_JointVelocities_FIELDLIST(X, a) \
  X(a, STATIC, REPEATED, DOUBLE, values, 1)
#define kuka_motion_external_JointVelocities_CALLBACK NULL
#define kuka_motion_external_JointVelocities_DEFAULT NULL

#define kuka_motion_external_JointTorques_FIELDLIST(X, a) X(a, STATIC, REPEATED, DOUBLE, values, 1)
#define kuka_motion_external_JointTorques_CALLBACK NULL
#define kuka_motion_external_JointTorques_DEFAULT NULL

#define kuka_motion_external_Vector_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, x, 1)              \
  X(a, STATIC, SINGULAR, DOUBLE, y, 2)              \
  X(a, STATIC, SINGULAR, DOUBLE, z, 3)
#define kuka_motion_external_Vector_CALLBACK NULL
#define kuka_motion_external_Vector_DEFAULT NULL

#define kuka_motion_external_Quaternion_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, DOUBLE, x, 1)                  \
  X(a, STATIC, SINGULAR, DOUBLE, y, 2)                  \
  X(a, STATIC, SINGULAR, DOUBLE, z, 3)                  \
  X(a, STATIC, SINGULAR, DOUBLE, w, 4)
#define kuka_motion_external_Quaternion_CALLBACK NULL
#define kuka_motion_external_Quaternion_DEFAULT NULL

#define kuka_motion_external_Twist_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, linear, 1)       \
  X(a, STATIC, OPTIONAL, MESSAGE, angular, 2)
#define kuka_motion_external_Twist_CALLBACK NULL
#define kuka_motion_external_Twist_DEFAULT NULL
#define kuka_motion_external_Twist_linear_MSGTYPE kuka_motion_external_Vector
#define kuka_motion_external_Twist_angular_MSGTYPE kuka_motion_external_Vector

#define kuka_motion_external_Wrench_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, force, 1)         \
  X(a, STATIC, OPTIONAL, MESSAGE, torque, 2)
#define kuka_motion_external_Wrench_CALLBACK NULL
#define kuka_motion_external_Wrench_DEFAULT NULL
#define kuka_motion_external_Wrench_force_MSGTYPE kuka_motion_external_Vector
#define kuka_motion_external_Wrench_torque_MSGTYPE kuka_motion_external_Vector

#define kuka_motion_external_Transform_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, translation, 1)      \
  X(a, STATIC, OPTIONAL, MESSAGE, rotation, 2)
#define kuka_motion_external_Transform_CALLBACK NULL
#define kuka_motion_external_Transform_DEFAULT NULL
#define kuka_motion_external_Transform_translation_MSGTYPE kuka_motion_external_Vector
#define kuka_motion_external_Transform_rotation_MSGTYPE kuka_motion_external_Quaternion

extern const pb_msgdesc_t kuka_motion_external_JointPositions_msg;
extern const pb_msgdesc_t kuka_motion_external_JointVelocities_msg;
extern const pb_msgdesc_t kuka_motion_external_JointTorques_msg;
extern const pb_msgdesc_t kuka_motion_external_Vector_msg;
extern const pb_msgdesc_t kuka_motion_external_Quaternion_msg;
extern const pb_msgdesc_t kuka_motion_external_Twist_msg;
extern const pb_msgdesc_t kuka_motion_external_Wrench_msg;
extern const pb_msgdesc_t kuka_motion_external_Transform_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kuka_motion_external_JointPositions_fields &kuka_motion_external_JointPositions_msg
#define kuka_motion_external_JointVelocities_fields &kuka_motion_external_JointVelocities_msg
#define kuka_motion_external_JointTorques_fields &kuka_motion_external_JointTorques_msg
#define kuka_motion_external_Vector_fields &kuka_motion_external_Vector_msg
#define kuka_motion_external_Quaternion_fields &kuka_motion_external_Quaternion_msg
#define kuka_motion_external_Twist_fields &kuka_motion_external_Twist_msg
#define kuka_motion_external_Wrench_fields &kuka_motion_external_Wrench_msg
#define kuka_motion_external_Transform_fields &kuka_motion_external_Transform_msg

/* Maximum encoded size of messages (where known) */
#define kuka_motion_external_JointPositions_size 216
#define kuka_motion_external_JointTorques_size 216
#define kuka_motion_external_JointVelocities_size 216
#define kuka_motion_external_Quaternion_size 36
#define kuka_motion_external_Transform_size 67
#define kuka_motion_external_Twist_size 58
#define kuka_motion_external_Vector_size 27
#define kuka_motion_external_Wrench_size 58

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
