name: CI Fedora

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora_version: [38, 39]
    container:
      image: fedora:${{ matrix.fedora_version }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        #!/bin/bash
        dnf install -y cmake gcc-c++ protobuf-devel grpc-devel openssl-devel gtest-devel tinyxml2-devel

    - name: Build and install common SDK
      run: cmake -S upstream/kuka_external_control_sdk/kuka_external_control_sdk_common -B build/common -DCMAKE_INSTALL_PREFIX="$HOME/.local" && cmake --build build/common --parallel && cmake --install build/common

    - name: Build and install iiQKA (OS1)
      run: cmake -DBUILD_TESTING=1 -S kuka_external_control_sdk_iiqka -B build/iiqka-os1 -DCMAKE_INSTALL_PREFIX="$HOME/.local" && cmake --build build/iiqka-os1 --parallel && cmake --install build/iiqka-os1

    - name: Run iiQKA (OS1) tests
      run: ./build/iiqka-os1/iiqka/test_robot && ./build/iiqka-os1/iiqka/test_message_builder

    - name: Build and install iiQKA.OS2
      run: cmake -DBUILD_TESTING=1 -S upstream/kuka_external_control_sdk/kuka_external_control_sdk_iiqka2 -B build/iiqka-os2 -DCMAKE_INSTALL_PREFIX="$HOME/.local" -DCMAKE_PREFIX_PATH="$HOME/.local" && cmake --build build/iiqka-os2 --parallel && cmake --install build/iiqka-os2

    - name: Run iiQKA.OS2 tests
      run: ./build/iiqka-os2/test_iiqka2_message_builder && ./build/iiqka-os2/test_eki_client_parsing

    - name: Build examples
      run: cmake -S kuka_external_control_sdk_examples -B build/examples -DCMAKE_PREFIX_PATH="$HOME/.local" && cmake --build build/examples --parallel
